title: Yulleta's Homepage
page-top-title: Yulleta
top-section-bg-text: Interactive & Artistic Vision AI Researcher <br/> <h5> Towards Human-Centric & Intuitive AI </h5>
home-subtitle: Yulleta&ensp;|&ensp;Minkyung Kim
copyright-text: '&copy; Yulleta. All Rights Reserved.'
