title: Yulleta's Homepage
page-top-title: Yulleta
top-section-bg-text: Artistic Technician & Researcher in Creative AI <br/><br/> <h5> Merging Generative AI with Art, Design & Human Expression </h5>
home-subtitle: Yulleta&ensp;|&ensp;Minkyung Kim
copyright-text: '&copy; Yulleta. All Rights Reserved.'
